#ifndef TT_ADC_CFG_H
#define TT_ADC_CFG_H

#include "sam.h"
#include "bsp/pinout.h"

#define TTADC_NUM_CHANNELS 2
#define TTADC_NUM_TIMESLOTS 10

#define TTADC_CHANNEL_TMCU 0
#define TTADC_CHANNEL_TDRV 1

#define TTADC_TIMESLOT_0_CHANNEL TTADC_CHANNEL_TMCU
#define TTADC_TIMESLOT_0_MUXPOS ADC_INPUTCTRL_MUXPOS_TEMP_Val
#define TTADC_TIMESLOT_0_MUXNEG ADC_INPUTCTRL_MUXNEG_GND_Val

#define TTADC_TIMESLOT_1_CHANNEL TTADC_CHANNEL_TDRV
#define TTADC_TIMESLOT_1_MUXPOS BOARD_NTC_ADC_INPUT
#define TTADC_TIMESLOT_1_MUXNEG ADC_INPUTCTRL_MUXNEG_GND_Val

#endif // TT_ADC_CFG_H
