#if !defined(BSP_PINOUT_H_)
#define BSP_PINOUT_H_

#include "hal/gpio.h"
#include "hal/sercom_usart.h"

// TODO: isn't great that we include it, since it could transitively end up in the app
#include "sam.h"

/** AL8891 LED driver IC pins */
#define AL8891_ENABLE_PORT PORT_GROUP_A
#define AL8891_ENABLE_PIN 0

#define AL8891_FAULT_PORT PORT_GROUP_A
#define AL8891_FAULT_PIN 1
#define AL8891_FAULT_PINMUX MUX_PA01A_EIC_EXTINT1

#define AL8891_ADIM_PORT PORT_GROUP_A
#define AL8891_ADIM_PIN 2
#define AL8891_ADIM_PINMUX MUX_PA02B_DAC_VOUT

#define AL8891_PDIM_PORT PORT_GROUP_A
#define AL8891_PDIM_PIN 3               // PDIM is GPIO only, TCC3 is not available on ATSAMD21E18A

#define AL8891_MON_PORT PORT_GROUP_A
#define AL8891_MON_PIN 4
#define AL8891_MON_PINMUX MUX_PA04B_ADC0_AIN4
#define AL8891_MON_ADC_INPUT ADC_INPUTCTRL_MUXPOS_PIN4_Val

/** Board NTC (Negative Temperature Coefficient) thermistor pins */
#define BOARD_NTC_PORT PORT_GROUP_A
#define BOARD_NTC_PIN 5
#define BOARD_NTC_PINMUX MUX_PA05B_ADC0_AIN5
#define BOARD_NTC_ADC_INPUT ADC_INPUTCTRL_MUXPOS_PIN5_Val

/** Board VBUS sense pins */
#define BOARD_VBUS_SENSE_PORT PORT_GROUP_A
#define BOARD_VBUS_SENSE_PIN 6
#define BOARD_VBUS_SENSE_PINMUX MUX_PA06B_ADC0_AIN6
#define BOARD_VBUS_SENSE_ADC_INPUT ADC_INPUTCTRL_MUXPOS_PIN6_Val

/** UART pins */
#define UART_SERCOM_INSTANCE SERCOM0

#define UART_CS_PORT PORT_GROUP_A
#define UART_CS_PIN 7

#define UART_TX_PORT PORT_GROUP_A
#define UART_TX_PIN 8
#define UART_TX_PINMUX MUX_PA08C_SERCOM0_PAD0

#define UART_RX_PORT PORT_GROUP_A
#define UART_RX_PIN 9
#define UART_RX_PINMUX MUX_PA09C_SERCOM0_PAD1

#define UART_TX_PAD SERCOM_USART_TX_PAD0
#define UART_RX_PAD SERCOM_USART_RX_PAD1

/** BMA456 3-axis accelerometer pins */
#define BMA456_SERCOM_INSTANCE SERCOM3

#define BMA456_SPI_MISO_PORT PORT_GROUP_A
#define BMA456_SPI_MISO_PIN 25
#define BMA456_SPI_MISO_PINMUX MUX_PA25C_SERCOM3_PAD3

#define BMA456_SPI_SCK_PORT PORT_GROUP_A
#define BMA456_SPI_SCK_PIN 23
#define BMA456_SPI_SCK_PINMUX MUX_PA23C_SERCOM3_PAD1

#define BMA456_SPI_CS_PORT PORT_GROUP_A
#define BMA456_SPI_CS_PIN 24

#define BMA456_SPI_MOSI_PORT PORT_GROUP_A
#define BMA456_SPI_MOSI_PIN 22
#define BMA456_SPI_MOSI_PINMUX MUX_PA22C_SERCOM3_PAD0

#define BMA456_INT1_PORT PORT_GROUP_A
#define BMA456_INT1_PIN 27
#define BMA456_INT1_PINMUX MUX_PA27A_EIC_EXTINT7

/** XM125 Radar pins */
#define XM125_SERCOM_INSTANCE SERCOM2
#define XM125_I2C_INSTANCE SERCOM1

#define XM125_RESET_PORT PORT_GROUP_A
#define XM125_RESET_PIN 10

#define XM125_WAKE_PORT PORT_GROUP_A
#define XM125_WAKE_PIN 11

#define XM125_TX_PORT PORT_GROUP_A
#define XM125_TX_PIN 14
#define XM125_TX_PINMUX MUX_PA14C_SERCOM2_PAD2
#define XM125_TX_PAD SERCOM_USART_TX_PAD2

#define XM125_RX_PORT PORT_GROUP_A
#define XM125_RX_PIN 15
#define XM125_RX_PINMUX MUX_PA15C_SERCOM2_PAD3
#define XM125_RX_PAD SERCOM_USART_RX_PAD3

#define XM125_SDA_PORT PORT_GROUP_A
#define XM125_SDA_PIN 16
#define XM125_SDA_PINMUX MUX_PA16C_SERCOM1_PAD0

#define XM125_SCL_PORT PORT_GROUP_A
#define XM125_SCL_PIN 17
#define XM125_SCL_PINMUX MUX_PA17C_SERCOM1_PAD1

#define XM125_INT_PORT PORT_GROUP_A
#define XM125_INT_PIN 18
#define XM125_INT_PINMUX MUX_PA18A_EIC_EXTINT2

#define XM125_BOOT_PORT PORT_GROUP_A
#define XM125_BOOT_PIN 19

#define XM125_GPIO0_PORT PORT_GROUP_A
#define XM125_GPIO0_PIN 28


#endif // BSP_PINOUT_H_
