#ifndef TT_ADC_CFG_H
#define TT_ADC_CFG_H

#include "sam.h"

#define TTADC_NUM_CHANNELS 3
#define TTADC_NUM_TIMESLOTS 10

#define TTADC_CHANNEL_TMCU 0
#define TTADC_CHANNEL_TDRV 1
#define TTADC_CHANNEL_VDRV 2

#define TTADC_TIMESLOT_0_CHANNEL TTADC_CHANNEL_TMCU
#define TTADC_TIMESLOT_0_MUXPOS 0
#define TTADC_TIMESLOT_0_MUXNEG 0

#define TTADC_TIMESLOT_1_CHANNEL TTADC_CHANNEL_TDRV
#define TTADC_TIMESLOT_1_MUXPOS 1
#define TTADC_TIMESLOT_1_MUXNEG 0

#define TTADC_TIMESLOT_2_CHANNEL TTADC_CHANNEL_VDRV
#define TTADC_TIMESLOT_2_MUXPOS 2
#define TTADC_TIMESLOT_2_MUXNEG 0

#endif // TT_ADC_CFG_H
