#if !defined(APP_CONFIG_H_)
#define APP_CONFIG_H_

/* --------------- Features ------------------- */
#define CONFIG_SYSTEM_TIME_INIT 1000

/* --------------- Settings ------------------- */
/* Brightness curve points */
#define CONFIG_BRIGHTNESS_CURVE_CUTOFF_X 100
#define CONFIG_BRIGHTNESS_CURVE_CUTOFF_Y 200
#define CONFIG_BRIGHTNESS_CURVE_MAX_X 800
#define CONFIG_BRIGHTNESS_CURVE_MAX_Y 800

/* Fixed brightness levels */
#define CONFIG_BRIGHTNESS_STANDARD_MIN_LEVEL 200
#define CONFIG_BRIGHTNESS_EMERGENCY_LEVEL 300
#define CONFIG_BRIGHTNESS_SAFETY_LEVEL 800

/* Brake light settings */
#define CONFIG_BRIGHTNESS_BRAKE_OFFSET 200

/* Strobe light settings */
#define CONFIG_BRIGHTNESS_STROBE_LOW_OFFSET 700
#define CONFIG_BRIGHTNESS_STROBE_HIGH_OFFSET 0

// Single strobe frequency: 30Hz
#define CONFIG_BRIGHTNESS_STROBE_SINGLE_ON_TIME 160
#define CONFIG_BRIGHTNESS_STROBE_SINGLE_OFF_TIME 160

// Rapid strobe pattern _______/¨\_/¨\_/¨\__
#define CONFIG_BRIGHTNESS_STROBE_RAPID_OFF_TIME 200
#define CONFIG_BRIGHTNESS_STROBE_RAPID_SWITCH_TIME 60

#define CONFIG_STROBE_SOURCE_DISABLED 0
#define CONFIG_STROBE_SOURCE_INTERNAL_SINGLE 1
#define CONFIG_STROBE_SOURCE_INTERNAL_RAPID 2
//TODO: external positive and negative

#define CONIFG_PRIMARY_STROBE_SOURCE CONFIG_STROBE_SOURCE_DISABLED
#define CONIFG_SAFETY_STROBE_SOURCE CONFIG_STROBE_SOURCE_DISABLED
#define CONIFG_EMERGENCY_STROBE_SOURCE CONFIG_STROBE_SOURCE_DISABLED

#endif // APP_CONFIG_H_
