#if !defined(APP_CONFIG_H_)
#define APP_CONFIG_H_

/* Brightness curve points */
#define CONFIG_BRIGHTNESS_CURVE_CUTOFF_X 10
#define CONFIG_BRIGHTNESS_CURVE_CUTOFF_Y 20
#define CONFIG_BRIGHTNESS_CURVE_MAX_X 80
#define CONFIG_BRIGHTNESS_CURVE_MAX_Y 80

/*  */
#define CONFIG_BRIGHTNESS_STANDARD_MIN_LEVEL 20
#define CONFIG_BRIGHTNESS_EMERGENCY_LEVEL 30
#define CONFIG_BRIGHTNESS_SAFETY_LEVEL 85

#define CONFIG_BRIGHTNESS_BRAKE_OFFSET 20

// TODO: when blinking should we use an offset from the brightness curve or a fixed low level?
#define CONFIG_BRIGHTNESS_STROBE_LOW_OFFSET 0
#define CONFIG_BRIGHTNESS_STROBE_HIGH_OFFSET 10

#endif // APP_CONFIG_H_
